name: M3U Statistics Updater

on:
  push:
    paths:
      - '**.m3u'
      - '!stats/**'
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Force update all M3U files (ignore last stats)'
        required: false
        default: 'false'
        type: boolean

jobs:
  update-m3u-stats:
    runs-on: ubuntu-latest
    
    # 添加权限配置
    permissions:
      contents: write  # 允许工作流写入仓库
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
        # 添加 token 配置
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tqdm

    - name: Run M3U statistics script
      run: |
        python .github/scripts/update_m3u_stats.py ${{ github.event_name == 'workflow_dispatch' && inputs.force_update || 'false' }}

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Update M3U statistics [skip ci]"
        git push
