name: M3U File Counter

on:
  push:
    paths:
      - '*.m3u'
  workflow_dispatch:

jobs:
  count-m3u8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Process each m3u file
        run: |
          M3U_FILES=$(ls *.m3u)
          for file in $M3U_FILES; do
            # Get previous count for this file
            COUNT_FILE="${file%.m3u}.count"
            if [ -f "$COUNT_FILE" ]; then
              PREV_COUNT=$(cat "$COUNT_FILE")
            else
              PREV_COUNT=0
            fi

            # Count m3u8 entries in this file
            COUNT=$(grep -c '\.m3u8$' "$file")

            # Calculate difference
            DIFF=$(($COUNT - $PREV_COUNT))
            if [ $DIFF -gt 0 ]; then
              DIFF_MSG="增加 $DIFF"
            elif [ $DIFF -lt 0 ]; then
              DIFF_MSG="删减 $((DIFF * -1))"
            else
              DIFF_MSG="无变化"
            fi

            # Update m3u file header
            DATE=$(date +"%Y%m%d")
            HEADER="$DATE-$COUNT-$DIFF_MSG"
            TEMP_FILE=$(mktemp)
            echo "# $HEADER" > $TEMP_FILE
            cat "$file" >> $TEMP_FILE
            mv $TEMP_FILE "$file"

            # Save current count for this file
            echo "$COUNT" > "$COUNT_FILE"
          done

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add *.m3u *.count
          if git diff-index --quiet HEAD --; then
            echo "No changes to commit."
          else
            git commit -m "Update m3u file headers with individual counts"
            git push
          fi    
