name: M3U/MP4 Statistics Updater

on:
  push:
    paths:
      - '**.m3u'
      - '!stats/**'
  workflow_dispatch:
    inputs:
      force_update:
        description: 'Force update all statistics'
        required: false
        default: 'false'
        type: boolean

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install tqdm

    - name: Run statistics script
      run: |
        python .github/scripts/update_stats.py \
          --force-update="${{ github.event_name == 'workflow_dispatch' && inputs.force_update || 'false' }}"

    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add -A
        git diff --quiet && git diff --staged --quiet || git commit -m "Update media statistics [skip ci]"
        git push

    - name: Refresh jsDelivr cache for M3U files
      run: |
        # Wait a few seconds to ensure changes are propagated
        sleep 10
        # 刷新当前项目的所有 M3U 文件
        curl "https://purge.jsdelivr.net/gh/${{github.repository}}/*.m3u"
        # 刷新其他项目的特定 M3U 文件（替换 user/repo-a 和文件名）:
        curl "https://purge.jsdelivr.net/gh/ParkCR/pintree@gh-pages/streaming/kbj.m3u"
        curl "https://purge.jsdelivr.net/gh/ParkCR/pintree@gh-pages/streaming/xdy.m3u"
